In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentance
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## DEFINE the vocabulary size
voc_size=10000


In [5]:
## one hot representation
one_hot_repr=[one_hot(words, voc_size)for words in sent]

In [6]:
one_hot_repr

[[5095, 8928, 956, 8299],
 [5095, 8928, 956, 8932],
 [5095, 1411, 956, 1588],
 [3710, 1339, 8508, 7486, 3544],
 [3710, 1339, 8508, 7486, 412],
 [1705, 5095, 9018, 956, 7771],
 [1475, 9508, 943, 7486]]

In [9]:
## word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [10]:
import numpy as pd

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5095 8928  956 8299]
 [   0    0    0    0 5095 8928  956 8932]
 [   0    0    0    0 5095 1411  956 1588]
 [   0    0    0 3710 1339 8508 7486 3544]
 [   0    0    0 3710 1339 8508 7486  412]
 [   0    0    0 1705 5095 9018  956 7771]
 [   0    0    0    0 1475 9508  943 7486]]


In [12]:
sent_length

8

In [16]:
## feature representation
dim=10


In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 86ms/step


2024-11-27 08:04:29.843104: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,
          0.04971156, -0.02864761, -0.01742949,  0.02705735,
          0.01715307,  0.03480449],
        [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,
          0.04971156, -0.02864761, -0.01742949,  0.02705735,
          0.01715307,  0.03480449],
        [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,
          0.04971156, -0.02864761, -0.01742949,  0.02705735,
          0.01715307,  0.03480449],
        [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,
          0.04971156, -0.02864761, -0.01742949,  0.02705735,
          0.01715307,  0.03480449],
        [ 0.04037276,  0.03294957, -0.00320654, -0.04246444,
         -0.04493063, -0.02340396, -0.00591906,  0.03790623,
          0.00060283,  0.00746164],
        [-0.01657214,  0.02817075, -0.00578128,  0.04742647,
          0.04858238, -0.01598857,  0.03532628,  0.04472819,
          0.01573927, -0.02926755],
        [-0.04206163, -0.02539467, -0.01924878, -0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 5095, 8928,  956, 8299], dtype=int32)

In [21]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 15ms/step


array([[-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,  0.04971156,
        -0.02864761, -0.01742949,  0.02705735,  0.01715307,  0.03480449],
       [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,  0.04971156,
        -0.02864761, -0.01742949,  0.02705735,  0.01715307,  0.03480449],
       [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,  0.04971156,
        -0.02864761, -0.01742949,  0.02705735,  0.01715307,  0.03480449],
       [-0.00713065,  0.0226403 ,  0.03525387,  0.0027437 ,  0.04971156,
        -0.02864761, -0.01742949,  0.02705735,  0.01715307,  0.03480449],
       [ 0.04037276,  0.03294957, -0.00320654, -0.04246444, -0.04493063,
        -0.02340396, -0.00591906,  0.03790623,  0.00060283,  0.00746164],
       [-0.01657214,  0.02817075, -0.00578128,  0.04742647,  0.04858238,
        -0.01598857,  0.03532628,  0.04472819,  0.01573927, -0.02926755],
       [-0.04206163, -0.02539467, -0.01924878, -0.04797242,  0.04772432,
        -0.01581584, -0.00756897,  0.02985135